const SCREEN_WIDTH = window.screen.width;
const MINUTES_IN_HOUR = 60;
const MAX_SHORT_FILM_DURATION = 40
let MOVIES_IN_ROW;
let NUMBER_OF_MOVIES_PER_PAGE;

if (SCREEN_WIDTH >= 1280) {
  MOVIES_IN_ROW = 3;
  NUMBER_OF_MOVIES_PER_PAGE = 12;
} else if (SCREEN_WIDTH < 1280 && SCREEN_WIDTH >= 761) {
  MOVIES_IN_ROW = 2;
  NUMBER_OF_MOVIES_PER_PAGE = 8;
} else {
  MOVIES_IN_ROW = 2;
  NUMBER_OF_MOVIES_PER_PAGE = 5;
}

export {
  MINUTES_IN_HOUR,
  MOVIES_IN_ROW,
  NUMBER_OF_MOVIES_PER_PAGE,
  MAX_SHORT_FILM_DURATION,
}